### ISSUE TITLE
9/18 ユーザからのフィードバック

### ISSUE THREAD

**Issue by hanazuki** [pepabo/railstutorial-android#124]
- スターに選ばれたとき，なるかどうか猶予がほしい（画面遷移のためにダイアログがでるのは煩わしい）
- 星形のアイコンわかりづらい / 別のユーザにみえる
- feedを下へスクロールした状態でプロフィールの変更をするとへんな位置にゆく
- ユーザの一覧に余白が多い
- パスワード変更後にフィードバックがない
- タイトルが変わらないので，画面を戻ったときにどこにいるか見失う(スターのいちらんなど)

**Comment by komaji** [comment]
- フォームでenterを押すと次の項目にいってほしい
- スターの説明はいつでも見れてほしい
- フォローまたはフォロワーがいないユーザの各一覧を見ると真っ白なので、何だ？となっていしまう
- メニューバーのJodoroidを押してしまう
- プロフィールのフィードを押すとフィードバックはあるが何も起きない
- 絵文字を使って投稿したときのエラー文がユーザ用になっていない
- toastが表示されるアクションを連続で行うとtoastが長い間表示される
- 投稿画面で画像選択すると上下に余白がでる

**Comment by hanazuki** [comment]
研修終了の2営業日前にレビュー会しても直しきれなかった
