### ISSUE TITLE
Floting action buttonの後ろがタップされてしまう

### ISSUE THREAD

**Issue by komaji** [pepabo/railstutorial-android#19]
Nexus5のAndoroid: 5.1.1では正常な動作確認ができたが、
Sony LT25iのAndoroid: 4.3ではボタンをタップしてもボタンの後ろがタップされたことになってしまう
 (連打するとたまに画面遷移する) のでなんとかする。 #18

**Comment by komaji** [comment]
# 現状

フラグメントとボタンを同一Layoutに設定してしている。

# 問題

おそらく、Layoutにフラグメントを貼り付ける際の位置がAndoroidのバージョンによって異なっており、Andoroid: 4.3ではボタンの手前に貼り付けられ、Andoroid: 5.1.1ではボタンの後ろに貼り付けられたことが原因でバージョンによって動作が異なったのでは。

# 解決策

ボタンを設定するためのLayoutを別に設けて、Layoutの段階で位置を決定することでフラグメントの手前にボタンが表示されるようになった。

**Comment by hfm** [comment]
> おそらく、Layoutにフラグメントを貼り付ける際の位置がAndoroidのバージョンによって異なっており、Andoroid: 4.3ではボタンの手前に貼り付けられ、Andoroid: 5.1.1ではボタンの後ろに貼り付けられたことが原因でバージョンによって動作が異なったのでは。

なるほど...!
