### ISSUE TITLE
投稿などを行った際に，自動でタイムライン等を更新する仕組みを作る

### ISSUE THREAD

**Issue by hanazuki** [pepabo/railstutorial-android#73]
投稿，投稿削除，ユーザ名変更，フォローなどの更新アクションを行ったときに，ドロワーに表示されている自分の名前，フィード，ユーザのフォロワー数などの表示に反映するための汎用的な仕組みを入れたい．

**Comment by hanazuki** [comment]
- あるPresenterがPOST/DELETE系のAPI呼び出しをしたときは，「どこか」にタイムスタンプを保存しておく
- ほかのPresenterはビューのonResumeのタイミングで，自分が最後にデータを取得した時間と「どこか」にあるタイムスタンプを比較して，自分のもっている情報が古くなっていればリロードを行う

という具合に実装したい

**Comment by hanazuki** [comment]
この「どこか」はなんて名前にすればよいかな……

**Comment by komaji** [comment]
「どこか」の名前は`Expiration Manager`になりました。

**Comment by hanazuki** [comment]
#107 で実装しました
