### ISSUE TITLE
最高のUX案

### ISSUE THREAD

**Issue by komaji** [pepabo/railstutorial-android#85]
- カスタマイズ機能
- 仏教系の画像が勝手についてくる
- ツイートすると仏教的な言葉に変換されてツイートされる
- ツイートとかするとポイントがたまってそれでガチャが回せる
  - ポイントは買うこともできる
- 画像のサイズをあげる
- チャットが出来る
- 下書きできる
  - 下書きしないとツイートできない
- ユーザの中から今週の仏が選出される
  - ツイートがすごい目立つ
  - フォローしてなくてもツイートが流れる
  - 人の下書きが見れる
- フォローされた時とかのプッシュ通知
- いいね！ボタン
  - なーむん、崇める、お線香
- スパム報告
  - 煩悩報告
- 階層を設ける
  - 煩悩階層、修行階層、浄土階層
  - 自分より上の階層の人しかフォローできない
  - いいね！たくさんもらうと上の階層に行ける
  - デフォルトが最高ランク
    - 108個煩悩を集めるとレベルダウン
- マークダウンでかける
- 位置情報
  - 現実世界の位置から浄土の位置を表示する
  - 山奥とかでツイートすると浄土ポイントがもらえる
  - ツイート数が多いところが今週の浄土になる
- Oauth
- リプライ
- 文字を大きくできる
- エラー処理を改良する
- カメラが直接起動するようにする
- 画像だけが並ぶページをつくる
- ネットに繋がっていないときはありがたい言葉が勝手に流れてくる

**Comment by horaotoko** [comment]
つられた

上に書いてあるのはすべて機能の話ですね。
UXなので、機能ではなくユーザーがどんな体験をするかを軸に話を展開しないといけないのでは？

**Comment by komaji** [comment]
なるほど...
その機能があるからなんなの？ってなってしまいますね。
ユーザがどんな体験をするかを交えてもう少し意見出しをしてみます！

**Comment by alotofwe** [comment]
> 仏教系の画像が勝手についてくる
> ツイートすると仏教的な言葉に変換されてツイートされる

5期生こわい...

**Comment by komaji** [comment]
> - ユーザの中から今週の仏が選出される
>   - フォローしてなくてもツイートが流れる

これを元に[スターシステム](https://docs.google.com/spreadsheets/d/1n0Y7FeegI3lV73Ranxtzo2uDudPc0GpFTJBGtDmAevs/edit#gid=0)を追加しました。
